## Read Files into RStudio

setwd("D:\\ProtectedNDVI") 

filenames <- gsub("\\.csv$","", list.files(pattern="\\.csv$"))

for(i in filenames){
  assign(i, read.csv(paste(i, ".csv", sep="")))
}

setwd("D:\\NonProtectedNDVI")

filenames <- gsub("\\.csv$","", list.files(pattern="\\.csv$"))

for(i in filenames){
  assign(i, read.csv(paste(i, ".csv", sep="")))
}


## Convert to Annual Means

{
  B1P$year <- substr(B1P$date, 7, 10)
  NDVI.yr1 <- tapply(B1P$mean, B1P$year, mean) 
  B2P$year <- substr(B2P$date, 7, 10)
  NDVI.yr2 <- tapply(B2P$mean, B2P$year, mean) 
  B3P$year <- substr(B3P$date, 7, 10)
  NDVI.yr3 <- tapply(B3P$mean, B3P$year, mean) 
  B4P$year <- substr(B4P$date, 7, 10)
  NDVI.yr4 <- tapply(B4P$mean, B4P$year, mean) 
  B5P$year <- substr(B5P$date, 7, 10)
  NDVI.yr5 <- tapply(B5P$mean, B5P$year, mean) 
  B6P$year <- substr(B6P$date, 7, 10)
  NDVI.yr6 <- tapply(B6P$mean, B6P$year, mean) 
  B7P$year <- substr(B7P$date, 7, 10)
  NDVI.yr7 <- tapply(B7P$mean, B7P$year, mean)
  B8P$year <- substr(B8P$date, 7, 10)
  NDVI.yr8 <- tapply(B8P$mean, B8P$year, mean) 
  B9P$year <- substr(B9P$date, 7, 10)
  NDVI.yr9 <- tapply(B9P$mean, B9P$year, mean) 
  B10P$year <- substr(B10P$date, 7, 10)
  NDVI.yr10 <- tapply(B10P$mean, B10P$year, mean) 
  
  G1P$year <- substr(G1P$date, 7, 10)
  NDVI.yr11 <- tapply(G1P$mean, G1P$year, mean) 
  G2P$year <- substr(G2P$date, 7, 10)
  NDVI.yr12 <- tapply(G2P$mean, G2P$year, mean) 
  G3P$year <- substr(G3P$date, 7, 10)
  NDVI.yr13 <- tapply(G3P$mean, G3P$year, mean) 
  G4P$year <- substr(G4P$date, 7, 10)
  NDVI.yr14 <- tapply(G4P$mean, G4P$year, mean) 
  G5P$year <- substr(G5P$date, 7, 10)
  NDVI.yr15 <- tapply(G5P$mean, G5P$year, mean) 
  G6P$year <- substr(G6P$date, 7, 10)
  NDVI.yr16 <- tapply(G6P$mean, G6P$year, mean) 
  G7P$year <- substr(G7P$date, 7, 10)
  NDVI.yr17 <- tapply(G7P$mean, G7P$year, mean) 
  G8P$year <- substr(G8P$date, 7, 10)
  NDVI.yr18 <- tapply(G1P$mean, G1P$year, mean) 
  G9P$year <- substr(G9P$date, 7, 10)
  NDVI.yr19 <- tapply(G9P$mean, G9P$year, mean) 
  G10P$year <- substr(G10P$date, 7, 10)
  NDVI.yr20 <- tapply(G10P$mean, G10P$year, mean) 
  G11P$year <- substr(G11P$date, 7, 10)
  NDVI.yr21 <- tapply(G11P$mean, G11P$year, mean) 
  G12P$year <- substr(G12P$date, 7, 10)
  NDVI.yr22 <- tapply(G12P$mean, G12P$year, mean) 
  G13P$year <- substr(G13P$date, 7, 10)
  NDVI.yr23 <- tapply(G13P$mean, G13P$year, mean) 
  G14P$year <- substr(G14P$date, 7, 10)
  NDVI.yr24 <- tapply(G14P$mean, G14P$year, mean) 
  G15P$year <- substr(G15P$date, 7, 10)
  NDVI.yr25 <- tapply(G15P$mean, G15P$year, mean)
  G16P$year <- substr(G16P$date, 7, 10)
  NDVI.yr26 <- tapply(G16P$mean, G16P$year, mean)
  G17P$year <- substr(G17P$date, 7, 10)
  NDVI.yr27 <- tapply(G17P$mean, G17P$year, mean) 
  G18P$year <- substr(G18P$date, 7, 10)
  NDVI.yr28 <- tapply(G18P$mean, G18P$year, mean) 
  G19P$year <- substr(G19P$date, 7, 10)
  NDVI.yr29 <- tapply(G19P$mean, G19P$year, mean) 
  G20P$year <- substr(G20P$date, 7, 10)
  NDVI.yr30 <- tapply(G20P$mean, G20P$year, mean)
  G21P$year <- substr(G21P$date, 7, 10)
  NDVI.yr31 <- tapply(G21P$mean, G21P$year, mean) 
  G22P$year <- substr(G22P$date, 7, 10)
  NDVI.yr32 <- tapply(G22P$mean, G22P$year, mean) 
  G23P$year <- substr(G23P$date, 7, 10)
  NDVI.yr33 <- tapply(G23P$mean, G23P$year, mean) 
  G24P$year <- substr(G24P$date, 7, 10)
  NDVI.yr34 <- tapply(G24P$mean, G24P$year, mean) 
  G25P$year <- substr(G25P$date, 7, 10)
  NDVI.yr35 <- tapply(G25P$mean, G25P$year, mean)
  G26P$year <- substr(G26P$date, 7, 10)
  NDVI.yr36 <- tapply(G26P$mean, G26P$year, mean) 
  G27P$year <- substr(G27P$date, 7, 10)
  NDVI.yr37 <- tapply(G27P$mean, G27P$year, mean) 
  G28P$year <- substr(G28P$date, 7, 10)
  NDVI.yr38 <- tapply(G28P$mean, G28P$year, mean) 
  G29P$year <- substr(G29P$date, 7, 10)
  NDVI.yr39 <- tapply(G29P$mean, G29P$year, mean)
  G30P$year <- substr(G30P$date, 7, 10)
  NDVI.yr40 <- tapply(G30P$mean, G30P$year, mean) 
  
  S1P$year <- substr(S1P$date, 7, 10)
  NDVI.yr41 <- tapply(S1P$mean, S1P$year, mean) 
  S2P$year <- substr(S2P$date, 7, 10)
  NDVI.yr42 <- tapply(S2P$mean, S2P$year, mean) 
  S3P$year <- substr(S3P$date, 7, 10)
  NDVI.yr43 <- tapply(S3P$mean, S3P$year, mean) 
  S4P$year <- substr(S4P$date, 7, 10)
  NDVI.yr44 <- tapply(S4P$mean, S4P$year, mean)
  S5P$year <- substr(S5P$date, 7, 10)
  NDVI.yr45 <- tapply(S5P$mean, S5P$year, mean) 
  S6P$year <- substr(S6P$date, 7, 10)
  NDVI.yr46 <- tapply(S6P$mean, S6P$year, mean) 
  S7P$year <- substr(S7P$date, 7, 10)
  NDVI.yr47 <- tapply(S7P$mean, S7P$year, mean)
  S8P$year <- substr(S8P$date, 7, 10)
  NDVI.yr48 <- tapply(S8P$mean, S8P$year, mean) 
  S9P$year <- substr(S9P$date, 7, 10)
  NDVI.yr49 <- tapply(S9P$mean, S9P$year, mean) 
  S10P$year <- substr(S10P$date, 7, 10)
  NDVI.yr50 <- tapply(S10P$mean, S10P$year, mean) 
  S11P$year <- substr(S11P$date, 7, 10)
  NDVI.yr51 <- tapply(S11P$mean, S11P$year, mean) 
  S12P$year <- substr(S12P$date, 7, 10)
  NDVI.yr52 <- tapply(S12P$mean, S12P$year, mean) 
  S13P$year <- substr(S13P$date, 7, 10)
  NDVI.yr53 <- tapply(S13P$mean, S13P$year, mean)
  S14P$year <- substr(S14P$date, 7, 10)
  NDVI.yr54 <- tapply(S14P$mean, S14P$year, mean) 
  S15P$year <- substr(S15P$date, 7, 10)
  NDVI.yr55 <- tapply(S15P$mean, S15P$year, mean)
  S16P$year <- substr(S16P$date, 7, 10)
  NDVI.yr56 <- tapply(S16P$mean, S16P$year, mean) 
  S17P$year <- substr(S17P$date, 7, 10)
  NDVI.yr57 <- tapply(S17P$mean, S17P$year, mean) 
  S18P$year <- substr(S18P$date, 7, 10)
  NDVI.yr58 <- tapply(S18P$mean, S18P$year, mean) 
  S19P$year <- substr(S19P$date, 7, 10)
  NDVI.yr59 <- tapply(S19P$mean, S19P$year, mean) 
  S20P$year <- substr(S20P$date, 7, 10)
  NDVI.yr60 <- tapply(S20P$mean, S20P$year, mean) 
  
  W1P$year <- substr(W1P$date, 7, 10)
  NDVI.yr61 <- tapply(W1P$mean, W1P$year, mean) 
  W2P$year <- substr(W2P$date, 7, 10)
  NDVI.yr62 <- tapply(W2P$mean, W2P$year, mean) 
  W3P$year <- substr(W3P$date, 7, 10)
  NDVI.yr63 <- tapply(W3P$mean, W3P$year, mean) 
  W4P$year <- substr(W4P$date, 7, 10)
  NDVI.yr64 <- tapply(W4P$mean, W4P$year, mean) 
  W5P$year <- substr(W5P$date, 7, 10)
  NDVI.yr65 <- tapply(W5P$mean, W5P$year, mean) 
  W6P$year <- substr(W6P$date, 7, 10)
  NDVI.yr66 <- tapply(W6P$mean, W6P$year, mean) 
  W7P$year <- substr(W7P$date, 7, 10)
  NDVI.yr67 <- tapply(W7P$mean, W7P$year, mean) 
  W8P$year <- substr(W8P$date, 7, 10)
  NDVI.yr68 <- tapply(W8P$mean, W8P$year, mean)
  W9P$year <- substr(W9P$date, 7, 10)
  NDVI.yr69 <- tapply(W9P$mean, W9P$year, mean) 
  W10P$year <- substr(W10P$date, 7, 10)
  NDVI.yr70 <- tapply(W10P$mean, W10P$year, mean)
  W11P$year <- substr(W11P$date, 7, 10)
  NDVI.yr71 <- tapply(W11P$mean, W11P$year, mean)
  W12P$year <- substr(W12P$date, 7, 10)
  NDVI.yr72 <- tapply(W12P$mean, W12P$year, mean)
  W13P$year <- substr(W13P$date, 7, 10)
  NDVI.yr73 <- tapply(W13P$mean, W13P$year, mean) 
  W14P$year <- substr(W14P$date, 7, 10)
  NDVI.yr74 <- tapply(W14P$mean, W14P$year, mean) 
  W15P$year <- substr(W15P$date, 7, 10)
  NDVI.yr75 <- tapply(W15P$mean, W15P$year, mean)
}

{
B1NP$year <- substr(B1NP$date, 7, 10)
NDVI.yr1a <- tapply(B1NP$mean, B1NP$year, mean) 
B2NP$year <- substr(B2NP$date, 7, 10)
NDVI.yr2a <- tapply(B2NP$mean, B2NP$year, mean) 
B3NP$year <- substr(B3NP$date, 7, 10)
NDVI.yr3a <- tapply(B3NP$mean, B3NP$year, mean) 
B4NP$year <- substr(B4NP$date, 7, 10)
NDVI.yr4a <- tapply(B4NP$mean, B4NP$year, mean) 
B5NP$year <- substr(B5NP$date, 7, 10)
NDVI.yr5a <- tapply(B5NP$mean, B5NP$year, mean)
B6NP$year <- substr(B6NP$date, 7, 10)
NDVI.yr6a <- tapply(B6NP$mean, B6NP$year, mean)
B7NP$year <- substr(B7NP$date, 7, 10)
NDVI.yr7a <- tapply(B7NP$mean, B7NP$year, mean) 
B8NP$year <- substr(B8NP$date, 7, 10)
NDVI.yr8a <- tapply(B8NP$mean, B8NP$year, mean) 
B9NP$year <- substr(B9NP$date, 7, 10)
NDVI.yr9a <- tapply(B9NP$mean, B9NP$year, mean) 
B10NP$year <- substr(B10NP$date, 7, 10)
NDVI.yr10a <- tapply(B10NP$mean, B10NP$year, mean) 

G1NP$year <- substr(G1NP$date, 7, 10)
NDVI.yr11a <- tapply(G1NP$mean, G1NP$year, mean) 
G2NP$year <- substr(G2NP$date, 7, 10)
NDVI.yr12a <- tapply(G2NP$mean, G2NP$year, mean) 
G3NP$year <- substr(G3NP$date, 7, 10)
NDVI.yr13a <- tapply(G3NP$mean, G3NP$year, mean) 
G4NP$year <- substr(G4NP$date, 7, 10)
NDVI.yr14a <- tapply(G4NP$mean, G4NP$year, mean) 
G5NP$year <- substr(G5NP$date, 7, 10)
NDVI.yr15a <- tapply(G5NP$mean, G5NP$year, mean)
G6NP$year <- substr(G6NP$date, 7, 10)
NDVI.yr16a <- tapply(G6NP$mean, G6NP$year, mean)
G7NP$year <- substr(G7NP$date, 7, 10)
NDVI.yr17a <- tapply(G7NP$mean, G7NP$year, mean) 
G8NP$year <- substr(G8NP$date, 7, 10)
NDVI.yr18a <- tapply(G1NP$mean, G1NP$year, mean) 
G9NP$year <- substr(G9NP$date, 7, 10)
NDVI.yr19a <- tapply(G9NP$mean, G9NP$year, mean) 
G10NP$year <- substr(G10NP$date, 7, 10)
NDVI.yr20a <- tapply(G10NP$mean, G10NP$year, mean) 
G11NP$year <- substr(G11NP$date, 7, 10)
NDVI.yr21a <- tapply(G11NP$mean, G11NP$year, mean) 
G12NP$year <- substr(G12NP$date, 7, 10)
NDVI.yr22a <- tapply(G12NP$mean, G12NP$year, mean) 
G13NP$year <- substr(G13NP$date, 7, 10)
NDVI.yr23a <- tapply(G13NP$mean, G13NP$year, mean) 
G14NP$year <- substr(G14NP$date, 7, 10)
NDVI.yr24a <- tapply(G14NP$mean, G14NP$year, mean)
G15NP$year <- substr(G15NP$date, 7, 10)
NDVI.yr25a <- tapply(G15NP$mean, G15NP$year, mean) 
G16NP$year <- substr(G16NP$date, 7, 10)
NDVI.yr26a <- tapply(G16NP$mean, G16NP$year, mean) 
G17NP$year <- substr(G17NP$date, 7, 10)
NDVI.yr27a <- tapply(G17NP$mean, G17NP$year, mean) 
G18NP$year <- substr(G18NP$date, 7, 10)
NDVI.yr28a <- tapply(G18NP$mean, G18NP$year, mean)
G19NP$year <- substr(G19NP$date, 7, 10)
NDVI.yr29a <- tapply(G19NP$mean, G19NP$year, mean) 
G20NP$year <- substr(G20NP$date, 7, 10)
NDVI.yr30a <- tapply(G20NP$mean, G20NP$year, mean)
G21NP$year <- substr(G21NP$date, 7, 10)
NDVI.yr31a <- tapply(G21NP$mean, G21NP$year, mean)
G22NP$year <- substr(G22NP$date, 7, 10)
NDVI.yr32a <- tapply(G22NP$mean, G22NP$year, mean)
G23NP$year <- substr(G23NP$date, 7, 10)
NDVI.yr33a <- tapply(G23NP$mean, G23NP$year, mean) 
G24NP$year <- substr(G24NP$date, 7, 10)
NDVI.yr34a <- tapply(G24NP$mean, G24NP$year, mean) 
G25NP$year <- substr(G25NP$date, 7, 10)
NDVI.yr35a <- tapply(G25NP$mean, G25NP$year, mean) 
G26NP$year <- substr(G26NP$date, 7, 10)
NDVI.yr36a <- tapply(G26NP$mean, G26NP$year, mean) 
G27NP$year <- substr(G27NP$date, 7, 10)
NDVI.yr37a <- tapply(G27NP$mean, G27NP$year, mean) 
G28NP$year <- substr(G28NP$date, 7, 10)
NDVI.yr38a <- tapply(G28NP$mean, G28NP$year, mean) 
G29NP$year <- substr(G29NP$date, 7, 10)
NDVI.yr39a <- tapply(G29NP$mean, G29NP$year, mean)
G30NP$year <- substr(G30NP$date, 7, 10)
NDVI.yr40a <- tapply(G30NP$mean, G30NP$year, mean) 

S1NP$year <- substr(S1NP$date, 7, 10)
NDVI.yr41a <- tapply(S1NP$mean, S1NP$year, mean) 
S2NP$year <- substr(S2NP$date, 7, 10)
NDVI.yr42a <- tapply(S2NP$mean, S2NP$year, mean) 
S3NP$year <- substr(S3NP$date, 7, 10)
NDVI.yr43a <- tapply(S3NP$mean, S3NP$year, mean) 
S4NP$year <- substr(S4NP$date, 7, 10)
NDVI.yr44a <- tapply(S4NP$mean, S4NP$year, mean) 
S5NP$year <- substr(S5NP$date, 7, 10)
NDVI.yr45a <- tapply(S5NP$mean, S5NP$year, mean) 
S6NP$year <- substr(S6NP$date, 7, 10)
NDVI.yr46a <- tapply(S6NP$mean, S6NP$year, mean) 
S7NP$year <- substr(S7NP$date, 7, 10)
NDVI.yr47a <- tapply(S7NP$mean, S7NP$year, mean)
S8NP$year <- substr(S8NP$date, 7, 10)
NDVI.yr48a <- tapply(S8NP$mean, S8NP$year, mean)
S9NP$year <- substr(S9NP$date, 7, 10)
NDVI.yr49a <- tapply(S9NP$mean, S9NP$year, mean)
S10NP$year <- substr(S10NP$date, 7, 10)
NDVI.yr50a <- tapply(S10NP$mean, S10NP$year, mean) 
S11NP$year <- substr(S11NP$date, 7, 10)
NDVI.yr51a <- tapply(S11NP$mean, S11NP$year, mean) 
S12NP$year <- substr(S12NP$date, 7, 10)
NDVI.yr52a <- tapply(S12NP$mean, S12NP$year, mean)
S13NP$year <- substr(S13NP$date, 7, 10)
NDVI.yr53a <- tapply(S13NP$mean, S13NP$year, mean) 
S14NP$year <- substr(S14NP$date, 7, 10)
NDVI.yr54a <- tapply(S14NP$mean, S14NP$year, mean)
S15NP$year <- substr(S15NP$date, 7, 10)
NDVI.yr55a <- tapply(S15NP$mean, S15NP$year, mean) 
S16NP$year <- substr(S16NP$date, 7, 10)
NDVI.yr56a <- tapply(S16NP$mean, S16NP$year, mean) 
S17NP$year <- substr(S17NP$date, 7, 10)
NDVI.yr57a <- tapply(S17NP$mean, S17NP$year, mean) 
S18NP$year <- substr(S18NP$date, 7, 10)
NDVI.yr58a <- tapply(S18NP$mean, S18NP$year, mean) 
S19NP$year <- substr(S19NP$date, 7, 10)
NDVI.yr59a <- tapply(S19NP$mean, S19NP$year, mean) 
S20NP$year <- substr(S20NP$date, 7, 10)
NDVI.yr60a <- tapply(S20NP$mean, S20NP$year, mean)

W1NP$year <- substr(W1NP$date, 7, 10)
NDVI.yr61a <- tapply(W1NP$mean, W1NP$year, mean) 
W2NP$year <- substr(W2NP$date, 7, 10)
NDVI.yr62a <- tapply(W2NP$mean, W2NP$year, mean)
W3NP$year <- substr(W3NP$date, 7, 10)
NDVI.yr63a <- tapply(W3NP$mean, W3NP$year, mean) 
W4NP$year <- substr(W4NP$date, 7, 10)
NDVI.yr64a <- tapply(W4NP$mean, W4NP$year, mean) 
W5NP$year <- substr(W5NP$date, 7, 10)
NDVI.yr65a <- tapply(W5NP$mean, W5NP$year, mean) 
W6NP$year <- substr(W6NP$date, 7, 10)
NDVI.yr66a <- tapply(W6NP$mean, W6NP$year, mean) 
W7NP$year <- substr(W7NP$date, 7, 10)
NDVI.yr67a <- tapply(W7NP$mean, W7NP$year, mean) 
W8NP$year <- substr(W8NP$date, 7, 10)
NDVI.yr68a <- tapply(W8NP$mean, W8NP$year, mean) 
W9NP$year <- substr(W9NP$date, 7, 10)
NDVI.yr69a <- tapply(W9NP$mean, W9NP$year, mean) 
W10NP$year <- substr(W10NP$date, 7, 10)
NDVI.yr70a <- tapply(W10NP$mean, W10NP$year, mean) 
W11NP$year <- substr(W11NP$date, 7, 10)
NDVI.yr71a <- tapply(W11NP$mean, W11NP$year, mean) 
W12NP$year <- substr(W12NP$date, 7, 10)
NDVI.yr72a <- tapply(W12NP$mean, W12NP$year, mean) 
W13NP$year <- substr(W13NP$date, 7, 10)
NDVI.yr73a <- tapply(W13NP$mean, W13NP$year, mean)
W14NP$year <- substr(W14NP$date, 7, 10)
NDVI.yr74a <- tapply(W14NP$mean, W14NP$year, mean) 
W15NP$year <- substr(W15NP$date, 7, 10)
NDVI.yr75a <- tapply(W15NP$mean, W15NP$year, mean) 
}


## Plot NDVI Time Series Graphs

# Protected Areas
{
plot(1,type='n',xlim=c(1,19),ylim=c(0,0.5),xlab="", ylab='Annual Mean NDVI', main="Protected Areas", xaxt="n")
  xtick<-seq(1, 19, by=2)
  axis(side=1, at=xtick, labels = FALSE)
  text(x=xtick,  labels= c("2001","2003", "2005", "2007", "2009", "2011", "2013", "2015", "2017", "2019"), 
       par("usr")[3], srt = 0, pos = 1, xpd = TRUE)
lines(NDVI.yr1, col="red")
lines(NDVI.yr3)
lines(NDVI.yr4)
lines(NDVI.yr5)
lines(NDVI.yr6)
lines(NDVI.yr7)
lines(NDVI.yr8)
lines(NDVI.yr9)
lines(NDVI.yr10)
lines(NDVI.yr11, col="red")  # the lines for plots in regions with >500mm annual rainfall coloured red
lines(NDVI.yr12, col="red")
lines(NDVI.yr13, col="red")
lines(NDVI.yr14, col="red")
lines(NDVI.yr15, col="red")
lines(NDVI.yr16, col="red")
lines(NDVI.yr17)
lines(NDVI.yr18)
lines(NDVI.yr19)
lines(NDVI.yr20)
lines(NDVI.yr21)
lines(NDVI.yr22)
lines(NDVI.yr23)
lines(NDVI.yr24)
lines(NDVI.yr25)
lines(NDVI.yr26)
lines(NDVI.yr27)
lines(NDVI.yr28)
lines(NDVI.yr29)
lines(NDVI.yr30)
lines(NDVI.yr31)
lines(NDVI.yr32)
lines(NDVI.yr33)
lines(NDVI.yr34)
lines(NDVI.yr35)
lines(NDVI.yr36)
lines(NDVI.yr37)
lines(NDVI.yr38)
lines(NDVI.yr39)
lines(NDVI.yr40)
lines(NDVI.yr41)
lines(NDVI.yr42)
lines(NDVI.yr43)
lines(NDVI.yr44)
lines(NDVI.yr45)
lines(NDVI.yr46)
lines(NDVI.yr47)
lines(NDVI.yr48)
lines(NDVI.yr49)
lines(NDVI.yr50)
lines(NDVI.yr51)
lines(NDVI.yr52)
lines(NDVI.yr53, col="red")
lines(NDVI.yr54, col="red")
lines(NDVI.yr55, col="red")
lines(NDVI.yr56, col="red")
lines(NDVI.yr57)
lines(NDVI.yr58)
lines(NDVI.yr59)
lines(NDVI.yr60)
lines(NDVI.yr61)
lines(NDVI.yr62)
lines(NDVI.yr63)
lines(NDVI.yr64)
lines(NDVI.yr65)
lines(NDVI.yr66)
lines(NDVI.yr67)
lines(NDVI.yr68)
lines(NDVI.yr69)
lines(NDVI.yr70)
lines(NDVI.yr71)
lines(NDVI.yr72)
lines(NDVI.yr73, col="red")
lines(NDVI.yr74, col="red")
lines(NDVI.yr75, col="red")
}

legend("topleft", legend=c("> 500mm","< 500mm"), col=c("red","black"), lty=1:1, title="   Mean Annual Rainfall   ")

# Non-Protected Areas
{
plot(1,type='n',xlim=c(1,19),ylim=c(0,0.5),xlab='', ylab='Annual Mean NDVI', , main="Non-Protected Areas", xaxt="n")
   xtick<-seq(1, 19, by=2)
   axis(side=1, at=xtick, labels = FALSE)
   text(x=xtick,  labels= c("2001","2003", "2005", "2007", "2009", "2011", "2013", "2015", "2017", "2019"), 
       par("usr")[3], srt = 0, pos = 1, xpd = TRUE)
lines(NDVI.yr1a)
lines(NDVI.yr2a)
lines(NDVI.yr3a)
lines(NDVI.yr4a)
lines(NDVI.yr5a, col="red")
lines(NDVI.yr6a, col="red")
lines(NDVI.yr7a)
lines(NDVI.yr8a)
lines(NDVI.yr9a, col="red")
lines(NDVI.yr10a)
lines(NDVI.yr11a)
lines(NDVI.yr12a)
lines(NDVI.yr13a)
lines(NDVI.yr14a)
lines(NDVI.yr15a)
lines(NDVI.yr16a)
lines(NDVI.yr17a)
lines(NDVI.yr18a, col="red")
lines(NDVI.yr19a, col="red")
lines(NDVI.yr20a, col="red")
lines(NDVI.yr21a, col="red")
lines(NDVI.yr22a, col="red")
lines(NDVI.yr23a, col="red")
lines(NDVI.yr24a, col="red")
lines(NDVI.yr25a)
lines(NDVI.yr26a)
lines(NDVI.yr27a)
lines(NDVI.yr28a)
lines(NDVI.yr29a)
lines(NDVI.yr30a)
lines(NDVI.yr31a)
lines(NDVI.yr32a)
lines(NDVI.yr33a)
lines(NDVI.yr34a)
lines(NDVI.yr35a)
lines(NDVI.yr36a)
lines(NDVI.yr37a)
lines(NDVI.yr38a)
lines(NDVI.yr39a)
lines(NDVI.yr40a)
lines(NDVI.yr41a)
lines(NDVI.yr42a, col="red")
lines(NDVI.yr43a, col="red")
lines(NDVI.yr44a)
lines(NDVI.yr45a)
lines(NDVI.yr46a)
lines(NDVI.yr47a)
lines(NDVI.yr48a)
lines(NDVI.yr49a)
lines(NDVI.yr50a)
lines(NDVI.yr51a)
lines(NDVI.yr52a)
lines(NDVI.yr53a)
lines(NDVI.yr54a)
lines(NDVI.yr55a)
lines(NDVI.yr56a)
lines(NDVI.yr57a)
lines(NDVI.yr58a)
lines(NDVI.yr59a)
lines(NDVI.yr60a)
lines(NDVI.yr61a)
lines(NDVI.yr62a)
lines(NDVI.yr63a)
lines(NDVI.yr64a)
lines(NDVI.yr65a)
lines(NDVI.yr66a, col="red")
lines(NDVI.yr67a, col="red")
lines(NDVI.yr68a, col="red")
lines(NDVI.yr69a, col="red")
lines(NDVI.yr70a, col="red")
lines(NDVI.yr71a)
lines(NDVI.yr72a)
lines(NDVI.yr73a)
lines(NDVI.yr74a)
lines(NDVI.yr75a, col="red")
}


## Merge Data for All Plots into One Dataframe

{
NDVI1 <- cbind(read.table(text=names(NDVI.yr1)),NDVI.yr1)  # converts vector to dataframe
colnames(NDVI1) <- c("year","mean")                        # renames the headings as "year" and "mean"
NDVI1$plot <- as.factor(1)                                 # adds a unique plot number identifier
NDVI2 <- cbind(read.table(text=names(NDVI.yr2)),NDVI.yr2)
colnames(NDVI2) <- c("year","mean")
NDVI2$plot <- as.factor(2) 
NDVI3 <- cbind(read.table(text=names(NDVI.yr3)),NDVI.yr3)
colnames(NDVI3) <- c("year","mean")
NDVI3$plot <- as.factor(3)
NDVI4 <- cbind(read.table(text=names(NDVI.yr4)),NDVI.yr4)
colnames(NDVI4) <- c("year","mean")
NDVI4$plot <- as.factor(4)
NDVI5 <- cbind(read.table(text=names(NDVI.yr5)),NDVI.yr5)
colnames(NDVI5) <- c("year","mean")
NDVI5$plot <- as.factor(5)
NDVI6 <- cbind(read.table(text=names(NDVI.yr6)),NDVI.yr6)
colnames(NDVI6) <- c("year","mean")
NDVI6$plot <- as.factor(6)
NDVI7 <- cbind(read.table(text=names(NDVI.yr7)),NDVI.yr7)
colnames(NDVI7) <- c("year","mean")
NDVI7$plot <- as.factor(7)
NDVI8 <- cbind(read.table(text=names(NDVI.yr8)),NDVI.yr8)
colnames(NDVI8) <- c("year","mean")
NDVI8$plot <- as.factor(8)
NDVI9 <- cbind(read.table(text=names(NDVI.yr9)),NDVI.yr9)
colnames(NDVI9) <- c("year","mean")
NDVI9$plot <- as.factor(9)
NDVI10 <- cbind(read.table(text=names(NDVI.yr10)),NDVI.yr10)
colnames(NDVI10) <- c("year","mean")
NDVI10$plot <- as.factor(10)
NDVI11 <- cbind(read.table(text=names(NDVI.yr11)),NDVI.yr11)
colnames(NDVI11) <- c("year","mean")
NDVI11$plot <- as.factor(11)
NDVI12 <- cbind(read.table(text=names(NDVI.yr12)),NDVI.yr12)
colnames(NDVI12) <- c("year","mean")
NDVI12$plot <- as.factor(12)
NDVI13 <- cbind(read.table(text=names(NDVI.yr13)),NDVI.yr13)
colnames(NDVI13) <- c("year","mean")
NDVI13$plot <- as.factor(13)
NDVI14 <- cbind(read.table(text=names(NDVI.yr14)),NDVI.yr14)
colnames(NDVI14) <- c("year","mean")
NDVI14$plot <- as.factor(14)
NDVI15 <- cbind(read.table(text=names(NDVI.yr15)),NDVI.yr15)
colnames(NDVI15) <- c("year","mean")
NDVI15$plot <- as.factor(15)
NDVI16 <- cbind(read.table(text=names(NDVI.yr16)),NDVI.yr16)
colnames(NDVI16) <- c("year","mean")
NDVI16$plot <- as.factor(16)
NDVI17 <- cbind(read.table(text=names(NDVI.yr17)),NDVI.yr17)
colnames(NDVI17) <- c("year","mean")
NDVI17$plot <- as.factor(17)
NDVI18 <- cbind(read.table(text=names(NDVI.yr18)),NDVI.yr18)
colnames(NDVI18) <- c("year","mean")
NDVI18$plot <- as.factor(18)
NDVI19 <- cbind(read.table(text=names(NDVI.yr19)),NDVI.yr19)
colnames(NDVI19) <- c("year","mean")
NDVI19$plot <- as.factor(19)
NDVI20 <- cbind(read.table(text=names(NDVI.yr20)),NDVI.yr20)
colnames(NDVI20) <- c("year","mean")
NDVI20$plot <-as.factor(20)
NDVI21 <- cbind(read.table(text=names(NDVI.yr21)),NDVI.yr21)
colnames(NDVI21) <- c("year","mean")
NDVI21$plot <- as.factor(21)
NDVI22 <- cbind(read.table(text=names(NDVI.yr22)),NDVI.yr22)
colnames(NDVI22) <- c("year","mean")
NDVI22$plot <- as.factor(22)
NDVI23 <- cbind(read.table(text=names(NDVI.yr23)),NDVI.yr23)
colnames(NDVI23) <- c("year","mean")
NDVI23$plot <- as.factor(23)
NDVI24 <- cbind(read.table(text=names(NDVI.yr24)),NDVI.yr24)
colnames(NDVI24) <- c("year","mean")
NDVI24$plot <- as.factor(24)
NDVI25 <- cbind(read.table(text=names(NDVI.yr25)),NDVI.yr25)
colnames(NDVI25) <- c("year","mean")
NDVI25$plot <- as.factor(25)
NDVI26 <- cbind(read.table(text=names(NDVI.yr26)),NDVI.yr26)
colnames(NDVI26) <- c("year","mean")
NDVI26$plot <- as.factor(26)
NDVI27 <- cbind(read.table(text=names(NDVI.yr27)),NDVI.yr27)
colnames(NDVI27) <- c("year","mean")
NDVI27$plot <- as.factor(27)
NDVI28 <- cbind(read.table(text=names(NDVI.yr28)),NDVI.yr28)
colnames(NDVI28) <- c("year","mean")
NDVI28$plot <- as.factor(28)
NDVI29 <- cbind(read.table(text=names(NDVI.yr29)),NDVI.yr29)
colnames(NDVI29) <- c("year","mean")
NDVI29$plot <- as.factor(29)
NDVI30 <- cbind(read.table(text=names(NDVI.yr30)),NDVI.yr30)
colnames(NDVI30) <- c("year","mean")
NDVI30$plot <- as.factor(30)
NDVI31 <- cbind(read.table(text=names(NDVI.yr31)),NDVI.yr31)
colnames(NDVI31) <- c("year","mean")
NDVI31$plot <- as.factor(31)
NDVI32 <- cbind(read.table(text=names(NDVI.yr32)),NDVI.yr32)
colnames(NDVI32) <- c("year","mean")
NDVI32$plot <- as.factor(32)
NDVI33 <- cbind(read.table(text=names(NDVI.yr33)),NDVI.yr33)
colnames(NDVI33) <- c("year","mean")
NDVI33$plot <- as.factor(33)
NDVI34 <- cbind(read.table(text=names(NDVI.yr34)),NDVI.yr34)
colnames(NDVI34) <- c("year","mean")
NDVI34$plot <- as.factor(34)
NDVI35 <- cbind(read.table(text=names(NDVI.yr35)),NDVI.yr35)
colnames(NDVI35) <- c("year","mean")
NDVI35$plot <- as.factor(35)
NDVI36 <- cbind(read.table(text=names(NDVI.yr36)),NDVI.yr36)
colnames(NDVI36) <- c("year","mean")
NDVI36$plot <- as.factor(36)
NDVI37 <- cbind(read.table(text=names(NDVI.yr37)),NDVI.yr37)
colnames(NDVI37) <- c("year","mean")
NDVI37$plot <- as.factor(37)
NDVI38 <- cbind(read.table(text=names(NDVI.yr38)),NDVI.yr38)
colnames(NDVI38) <- c("year","mean")
NDVI38$plot <- as.factor(38)
NDVI39 <- cbind(read.table(text=names(NDVI.yr39)),NDVI.yr39)
colnames(NDVI39) <- c("year","mean")
NDVI39$plot <- as.factor(39)
NDVI40 <- cbind(read.table(text=names(NDVI.yr40)),NDVI.yr40)
colnames(NDVI40) <- c("year","mean")
NDVI40$plot <- as.factor(40)
NDVI41 <- cbind(read.table(text=names(NDVI.yr41)),NDVI.yr41)
colnames(NDVI41) <- c("year","mean")
NDVI41$plot <- as.factor(41)
NDVI42 <- cbind(read.table(text=names(NDVI.yr42)),NDVI.yr42)
colnames(NDVI42) <- c("year","mean")
NDVI42$plot <- as.factor(42)
NDVI43 <- cbind(read.table(text=names(NDVI.yr43)),NDVI.yr43)
colnames(NDVI43) <- c("year","mean")
NDVI43$plot <- as.factor(43)
NDVI44 <- cbind(read.table(text=names(NDVI.yr44)),NDVI.yr44)
colnames(NDVI44) <- c("year","mean")
NDVI44$plot <- as.factor(44)
NDVI45 <- cbind(read.table(text=names(NDVI.yr45)),NDVI.yr45)
colnames(NDVI45) <- c("year","mean")
NDVI45$plot <- as.factor(45)
NDVI46 <- cbind(read.table(text=names(NDVI.yr46)),NDVI.yr46)
colnames(NDVI46) <- c("year","mean")
NDVI46$plot <- as.factor(46)
NDVI47 <- cbind(read.table(text=names(NDVI.yr47)),NDVI.yr47)
colnames(NDVI47) <- c("year","mean")
NDVI47$plot <- as.factor(47)
NDVI48 <- cbind(read.table(text=names(NDVI.yr48)),NDVI.yr48)
colnames(NDVI48) <- c("year","mean")
NDVI48$plot <- as.factor(48)
NDVI49 <- cbind(read.table(text=names(NDVI.yr49)),NDVI.yr49)
colnames(NDVI49) <- c("year","mean")
NDVI49$plot <- as.factor(49)
NDVI50 <- cbind(read.table(text=names(NDVI.yr50)),NDVI.yr50)
colnames(NDVI50) <- c("year","mean")
NDVI50$plot <- as.factor(50)
NDVI51 <- cbind(read.table(text=names(NDVI.yr51)),NDVI.yr51)
colnames(NDVI51) <- c("year","mean")
NDVI51$plot <- as.factor(51)
NDVI52 <- cbind(read.table(text=names(NDVI.yr52)),NDVI.yr52)
colnames(NDVI52) <- c("year","mean")
NDVI52$plot <- as.factor(52)
NDVI53 <- cbind(read.table(text=names(NDVI.yr53)),NDVI.yr53)
colnames(NDVI53) <- c("year","mean")
NDVI53$plot <- as.factor(53)
NDVI54 <- cbind(read.table(text=names(NDVI.yr54)),NDVI.yr54)
colnames(NDVI54) <- c("year","mean")
NDVI54$plot <- as.factor(54)
NDVI55 <- cbind(read.table(text=names(NDVI.yr55)),NDVI.yr55)
colnames(NDVI55) <- c("year","mean")
NDVI55$plot <- as.factor(55)
NDVI56 <- cbind(read.table(text=names(NDVI.yr56)),NDVI.yr56)
colnames(NDVI56) <- c("year","mean")
NDVI56$plot <- as.factor(56)
NDVI57 <- cbind(read.table(text=names(NDVI.yr57)),NDVI.yr57)
colnames(NDVI57) <- c("year","mean")
NDVI57$plot <- as.factor(57)
NDVI58 <- cbind(read.table(text=names(NDVI.yr58)),NDVI.yr58)
colnames(NDVI58) <- c("year","mean")
NDVI58$plot <- as.factor(58)
NDVI59 <- cbind(read.table(text=names(NDVI.yr59)),NDVI.yr59)
colnames(NDVI59) <- c("year","mean")
NDVI59$plot <- as.factor(59)
NDVI60 <- cbind(read.table(text=names(NDVI.yr60)),NDVI.yr60)
colnames(NDVI60) <- c("year","mean")
NDVI60$plot <- as.factor(60)
NDVI61 <- cbind(read.table(text=names(NDVI.yr61)),NDVI.yr61)
colnames(NDVI61) <- c("year","mean")
NDVI61$plot <- as.factor(61)
NDVI62 <- cbind(read.table(text=names(NDVI.yr62)),NDVI.yr62)
colnames(NDVI62) <- c("year","mean")
NDVI62$plot <- as.factor(62)
NDVI63 <- cbind(read.table(text=names(NDVI.yr63)),NDVI.yr63)
colnames(NDVI63) <- c("year","mean")
NDVI63$plot <- as.factor(63)
NDVI64 <- cbind(read.table(text=names(NDVI.yr64)),NDVI.yr64)
colnames(NDVI64) <- c("year","mean")
NDVI64$plot <- as.factor(64)
NDVI65 <- cbind(read.table(text=names(NDVI.yr65)),NDVI.yr65)
colnames(NDVI65) <- c("year","mean")
NDVI65$plot <- as.factor(65)
NDVI66 <- cbind(read.table(text=names(NDVI.yr66)),NDVI.yr66)
colnames(NDVI66) <- c("year","mean")
NDVI66$plot <- as.factor(66)
NDVI67 <- cbind(read.table(text=names(NDVI.yr67)),NDVI.yr67)
colnames(NDVI67) <- c("year","mean")
NDVI67$plot <- as.factor(67)
NDVI68 <- cbind(read.table(text=names(NDVI.yr68)),NDVI.yr68)
colnames(NDVI68) <- c("year","mean")
NDVI68$plot <- as.factor(68)
NDVI69 <- cbind(read.table(text=names(NDVI.yr69)),NDVI.yr69)
colnames(NDVI69) <- c("year","mean")
NDVI69$plot <- as.factor(69)
NDVI70 <- cbind(read.table(text=names(NDVI.yr70)),NDVI.yr70)
colnames(NDVI70) <- c("year","mean")
NDVI70$plot <- as.factor(70)
NDVI71 <- cbind(read.table(text=names(NDVI.yr71)),NDVI.yr71)
colnames(NDVI71) <- c("year","mean")
NDVI71$plot <- as.factor(71)
NDVI72 <- cbind(read.table(text=names(NDVI.yr72)),NDVI.yr72)
colnames(NDVI72) <- c("year","mean")
NDVI72$plot <- as.factor(72)
NDVI73 <- cbind(read.table(text=names(NDVI.yr73)),NDVI.yr73)
colnames(NDVI73) <- c("year","mean")
NDVI73$plot <- as.factor(73)
NDVI74 <- cbind(read.table(text=names(NDVI.yr74)),NDVI.yr74)
colnames(NDVI74) <- c("year","mean")
NDVI74$plot <- as.factor(74)
NDVI75 <- cbind(read.table(text=names(NDVI.yr75)),NDVI.yr75)
colnames(NDVI75) <- c("year","mean")
NDVI75$plot <- as.factor(75)
NDVI1a <- cbind(read.table(text=names(NDVI.yr1a)),NDVI.yr1a)
colnames(NDVI1a) <- c("year","mean")
NDVI1a$plot <- as.factor("1a")
NDVI2a <- cbind(read.table(text=names(NDVI.yr2a)),NDVI.yr2a)
colnames(NDVI2a) <- c("year","mean")
NDVI2a$plot <- as.factor("2a") 
NDVI3a <- cbind(read.table(text=names(NDVI.yr3a)),NDVI.yr3a)
colnames(NDVI3a) <- c("year","mean")
NDVI3a$plot <- as.factor("3a")
NDVI4a <- cbind(read.table(text=names(NDVI.yr4a)),NDVI.yr4a)
colnames(NDVI4a) <- c("year","mean")
NDVI4a$plot <- as.factor("4a")
NDVI5a <- cbind(read.table(text=names(NDVI.yr5a)),NDVI.yr5a)
colnames(NDVI5a) <- c("year","mean")
NDVI5a$plot <- as.factor("5a")
NDVI6a <- cbind(read.table(text=names(NDVI.yr6a)),NDVI.yr6a)
colnames(NDVI6a) <- c("year","mean")
NDVI6a$plot <- as.factor("6a")
NDVI7a <- cbind(read.table(text=names(NDVI.yr7a)),NDVI.yr7a)
colnames(NDVI7a) <- c("year","mean")
NDVI7a$plot <- as.factor("7a")
NDVI8a <- cbind(read.table(text=names(NDVI.yr8a)),NDVI.yr8a)
colnames(NDVI8a) <- c("year","mean")
NDVI8a$plot <- as.factor("8a")
NDVI9a <- cbind(read.table(text=names(NDVI.yr9a)),NDVI.yr9a)
colnames(NDVI9a) <- c("year","mean")
NDVI9a$plot <- as.factor("9a")
NDVI10a <- cbind(read.table(text=names(NDVI.yr10a)),NDVI.yr10a)
colnames(NDVI10a) <- c("year","mean")
NDVI10a$plot <- as.factor("10a")
NDVI11a <- cbind(read.table(text=names(NDVI.yr11a)),NDVI.yr11a)
colnames(NDVI11a) <- c("year","mean")
NDVI11a$plot <- as.factor("11a")
NDVI12a <- cbind(read.table(text=names(NDVI.yr12a)),NDVI.yr12a)
colnames(NDVI12a) <- c("year","mean")
NDVI12a$plot <- as.factor("12a")
NDVI13a <- cbind(read.table(text=names(NDVI.yr13a)),NDVI.yr13a)
colnames(NDVI13a) <- c("year","mean")
NDVI13a$plot <- as.factor("13a")
NDVI14a <- cbind(read.table(text=names(NDVI.yr14a)),NDVI.yr14a)
colnames(NDVI14a) <- c("year","mean")
NDVI14a$plot <- as.factor("14a")
NDVI15a <- cbind(read.table(text=names(NDVI.yr15a)),NDVI.yr15a)
colnames(NDVI15a) <- c("year","mean")
NDVI15a$plot <- as.factor("15a")
NDVI16a <- cbind(read.table(text=names(NDVI.yr16a)),NDVI.yr16a)
colnames(NDVI16a) <- c("year","mean")
NDVI16a$plot <- as.factor("16a")
NDVI17a <- cbind(read.table(text=names(NDVI.yr17a)),NDVI.yr17a)
colnames(NDVI17a) <- c("year","mean")
NDVI17a$plot <- as.factor("17a")
NDVI18a <- cbind(read.table(text=names(NDVI.yr18a)),NDVI.yr18a)
colnames(NDVI18a) <- c("year","mean")
NDVI18a$plot <- as.factor("18a")
NDVI19a <- cbind(read.table(text=names(NDVI.yr19a)),NDVI.yr19a)
colnames(NDVI19a) <- c("year","mean")
NDVI19a$plot <- as.factor("19a")
NDVI20a <- cbind(read.table(text=names(NDVI.yr20a)),NDVI.yr20a)
colnames(NDVI20a) <- c("year","mean")
NDVI20a$plot <-as.factor("20a")
NDVI21a <- cbind(read.table(text=names(NDVI.yr21a)),NDVI.yr21a)
colnames(NDVI21a) <- c("year","mean")
NDVI21a$plot <- as.factor("21a")
NDVI22a <- cbind(read.table(text=names(NDVI.yr22a)),NDVI.yr22a)
colnames(NDVI22a) <- c("year","mean")
NDVI22a$plot <- as.factor("22a")
NDVI23a <- cbind(read.table(text=names(NDVI.yr23a)),NDVI.yr23a)
colnames(NDVI23a) <- c("year","mean")
NDVI23a$plot <- as.factor("23a")
NDVI24a <- cbind(read.table(text=names(NDVI.yr24a)),NDVI.yr24a)
colnames(NDVI24a) <- c("year","mean")
NDVI24a$plot <- as.factor("24a")
NDVI25a <- cbind(read.table(text=names(NDVI.yr25a)),NDVI.yr25a)
colnames(NDVI25a) <- c("year","mean")
NDVI25a$plot <- as.factor("25a")
NDVI26a <- cbind(read.table(text=names(NDVI.yr26a)),NDVI.yr26a)
colnames(NDVI26a) <- c("year","mean")
NDVI26a$plot <- as.factor("26a")
NDVI27a <- cbind(read.table(text=names(NDVI.yr27a)),NDVI.yr27a)
colnames(NDVI27a) <- c("year","mean")
NDVI27a$plot <- as.factor("27a")
NDVI28a <- cbind(read.table(text=names(NDVI.yr28a)),NDVI.yr28a)
colnames(NDVI28a) <- c("year","mean")
NDVI28a$plot <- as.factor("28a")
NDVI29a <- cbind(read.table(text=names(NDVI.yr29a)),NDVI.yr29a)
colnames(NDVI29a) <- c("year","mean")
NDVI29a$plot <- as.factor("29a")
NDVI30a <- cbind(read.table(text=names(NDVI.yr30a)),NDVI.yr30a)
colnames(NDVI30a) <- c("year","mean")
NDVI30a$plot <- as.factor("30a")
NDVI31a <- cbind(read.table(text=names(NDVI.yr31a)),NDVI.yr31a)
colnames(NDVI31a) <- c("year","mean")
NDVI31a$plot <- as.factor("31a")
NDVI32a <- cbind(read.table(text=names(NDVI.yr32a)),NDVI.yr32a)
colnames(NDVI32a) <- c("year","mean")
NDVI32a$plot <- as.factor("32a")
NDVI33a <- cbind(read.table(text=names(NDVI.yr33a)),NDVI.yr33a)
colnames(NDVI33a) <- c("year","mean")
NDVI33a$plot <- as.factor("33a")
NDVI34a <- cbind(read.table(text=names(NDVI.yr34a)),NDVI.yr34a)
colnames(NDVI34a) <- c("year","mean")
NDVI34a$plot <- as.factor("34a")
NDVI35a <- cbind(read.table(text=names(NDVI.yr35a)),NDVI.yr35a)
colnames(NDVI35a) <- c("year","mean")
NDVI35a$plot <- as.factor("35a")
NDVI36a <- cbind(read.table(text=names(NDVI.yr36a)),NDVI.yr36a)
colnames(NDVI36a) <- c("year","mean")
NDVI36a$plot <- as.factor("36a")
NDVI37a <- cbind(read.table(text=names(NDVI.yr37a)),NDVI.yr37a)
colnames(NDVI37a) <- c("year","mean")
NDVI37a$plot <- as.factor("37a")
NDVI38a <- cbind(read.table(text=names(NDVI.yr38a)),NDVI.yr38a)
colnames(NDVI38a) <- c("year","mean")
NDVI38a$plot <- as.factor("38a")
NDVI39a <- cbind(read.table(text=names(NDVI.yr39a)),NDVI.yr39a)
colnames(NDVI39a) <- c("year","mean")
NDVI39a$plot <- as.factor("39a")
NDVI40a <- cbind(read.table(text=names(NDVI.yr40a)),NDVI.yr40a)
colnames(NDVI40a) <- c("year","mean")
NDVI40a$plot <- as.factor("40a")
NDVI41a <- cbind(read.table(text=names(NDVI.yr41a)),NDVI.yr41a)
colnames(NDVI41a) <- c("year","mean")
NDVI41a$plot <- as.factor("41a")
NDVI42a <- cbind(read.table(text=names(NDVI.yr42a)),NDVI.yr42a)
colnames(NDVI42a) <- c("year","mean")
NDVI42a$plot <- as.factor("42a")
NDVI43a <- cbind(read.table(text=names(NDVI.yr43a)),NDVI.yr43a)
colnames(NDVI43a) <- c("year","mean")
NDVI43a$plot <- as.factor("43a")
NDVI44a <- cbind(read.table(text=names(NDVI.yr44a)),NDVI.yr44a)
colnames(NDVI44a) <- c("year","mean")
NDVI44a$plot <- as.factor("44a")
NDVI45a <- cbind(read.table(text=names(NDVI.yr45a)),NDVI.yr45a)
colnames(NDVI45a) <- c("year","mean")
NDVI45a$plot <- as.factor("45a")
NDVI46a <- cbind(read.table(text=names(NDVI.yr46a)),NDVI.yr46a)
colnames(NDVI46a) <- c("year","mean")
NDVI46a$plot <- as.factor("46a")
NDVI47a <- cbind(read.table(text=names(NDVI.yr47a)),NDVI.yr47a)
colnames(NDVI47a) <- c("year","mean")
NDVI47a$plot <- as.factor("47a")
NDVI48a <- cbind(read.table(text=names(NDVI.yr48a)),NDVI.yr48a)
colnames(NDVI48a) <- c("year","mean")
NDVI48a$plot <- as.factor("48a")
NDVI49a <- cbind(read.table(text=names(NDVI.yr49a)),NDVI.yr49a)
colnames(NDVI49a) <- c("year","mean")
NDVI49a$plot <- as.factor("49a")
NDVI50a <- cbind(read.table(text=names(NDVI.yr50a)),NDVI.yr50a)
colnames(NDVI50a) <- c("year","mean")
NDVI50a$plot <- as.factor("50a")
NDVI51a <- cbind(read.table(tex=names(NDVI.yr51a)),NDVI.yr51a)
colnames(NDVI51a) <- c("year","mean")
NDVI51a$plot <- as.factor("51a")
NDVI52a <- cbind(read.table(text=names(NDVI.yr52a)),NDVI.yr52a)
colnames(NDVI52a) <- c("year","mean")
NDVI52a$plot <- as.factor("52a")
NDVI53a <- cbind(read.table(text=names(NDVI.yr53a)),NDVI.yr53a)
colnames(NDVI53a) <- c("year","mean")
NDVI53a$plot <- as.factor("53a")
NDVI54a <- cbind(read.table(text=names(NDVI.yr54a)),NDVI.yr54a)
colnames(NDVI54a) <- c("year","mean")
NDVI54a$plot <- as.factor("54a")
NDVI55a <- cbind(read.table(text=names(NDVI.yr55a)),NDVI.yr55a)
colnames(NDVI55a) <- c("year","mean")
NDVI55a$plot <- as.factor("55a")
NDVI56a <- cbind(read.table(text=names(NDVI.yr56a)),NDVI.yr56a)
colnames(NDVI56a) <- c("year","mean")
NDVI56a$plot <- as.factor("56a")
NDVI57a <- cbind(read.table(text=names(NDVI.yr57a)),NDVI.yr57a)
colnames(NDVI57a) <- c("year","mean")
NDVI57a$plot <- as.factor("57a")
NDVI58a <- cbind(read.table(text=names(NDVI.yr58a)),NDVI.yr58a)
colnames(NDVI58a) <- c("year","mean")
NDVI58a$plot <- as.factor("58a")
NDVI59a <- cbind(read.table(text=names(NDVI.yr59a)),NDVI.yr59a)
colnames(NDVI59a) <- c("year","mean")
NDVI59a$plot <- as.factor("59a")
NDVI60a <- cbind(read.table(text=names(NDVI.yr60a)),NDVI.yr60a)
colnames(NDVI60a) <- c("year","mean")
NDVI60a$plot <- as.factor("60a")
NDVI61a <- cbind(read.table(text=names(NDVI.yr61a)),NDVI.yr61a)
colnames(NDVI61a) <- c("year","mean")
NDVI61a$plot <- as.factor("61a")
NDVI62a <- cbind(read.table(text=names(NDVI.yr62a)),NDVI.yr62a)
colnames(NDVI62a) <- c("year","mean")
NDVI62a$plot <- as.factor("62a")
NDVI63a <- cbind(read.table(text=names(NDVI.yr63a)),NDVI.yr63a)
colnames(NDVI63a) <- c("year","mean")
NDVI63a$plot <- as.factor("63a")
NDVI64a <- cbind(read.table(text=names(NDVI.yr64a)),NDVI.yr64a)
colnames(NDVI64a) <- c("year","mean")
NDVI64a$plot <- as.factor("64a")
NDVI65a <- cbind(read.table(text=names(NDVI.yr65a)),NDVI.yr65a)
colnames(NDVI65a) <- c("year","mean")
NDVI65a$plot <- as.factor("65a")
NDVI66a <- cbind(read.table(text=names(NDVI.yr66a)),NDVI.yr66a)
colnames(NDVI66a) <- c("year","mean")
NDVI66a$plot <- as.factor("66a")
NDVI67a <- cbind(read.table(text=names(NDVI.yr67a)),NDVI.yr67a)
colnames(NDVI67a) <- c("year","mean")
NDVI67a$plot <- as.factor("67a")
NDVI68a <- cbind(read.table(text=names(NDVI.yr68a)),NDVI.yr68a)
colnames(NDVI68a) <- c("year","mean")
NDVI68a$plot <- as.factor("68a")
NDVI69a <- cbind(read.table(text=names(NDVI.yr69a)),NDVI.yr69a)
colnames(NDVI69a) <- c("year","mean")
NDVI69a$plot <- as.factor("69a")
NDVI70a <- cbind(read.table(text=names(NDVI.yr70a)),NDVI.yr70a)
colnames(NDVI70a) <- c("year","mean")
NDVI70a$plot <- as.factor("70a")
NDVI71a <- cbind(read.table(text=names(NDVI.yr71a)),NDVI.yr71a)
colnames(NDVI71a) <- c("year","mean")
NDVI71a$plot <- as.factor("71a")
NDVI72a <- cbind(read.table(text=names(NDVI.yr72a)),NDVI.yr72a)
colnames(NDVI72a) <- c("year","mean")
NDVI72a$plot <- as.factor("72a")
NDVI73a <- cbind(read.table(text=names(NDVI.yr73a)),NDVI.yr73a)
colnames(NDVI73a) <- c("year","mean")
NDVI73a$plot <- as.factor("73a")
NDVI74a <- cbind(read.table(text=names(NDVI.yr74a)),NDVI.yr74a)
colnames(NDVI74a) <- c("year","mean")
NDVI74a$plot <- as.factor("74a")
NDVI75a <- cbind(read.table(text=names(NDVI.yr75a)),NDVI.yr75a)
colnames(NDVI75a) <- c("year","mean")
NDVI75a$plot <- as.factor("75a")
}

NDVI <- rbind(NDVI1,NDVI2,NDVI3,NDVI4,NDVI5,NDVI6,NDVI7,NDVI8,NDVI9,NDVI10,             # combines all the indiviudal plot dataframes into one
              NDVI11,NDVI12,NDVI13,NDVI14,NDVI15,NDVI16,NDVI17,NDVI18,NDVI19,NDVI20,
              NDVI21,NDVI22,NDVI23,NDVI24,NDVI25,NDVI26,NDVI27,NDVI28,NDVI29,NDVI30,
              NDVI31,NDVI32,NDVI33,NDVI34,NDVI35,NDVI36,NDVI37,NDVI38,NDVI39,NDVI40,
              NDVI41,NDVI42,NDVI43,NDVI44,NDVI45,NDVI46,NDVI47,NDVI48,NDVI49,NDVI50,
              NDVI51,NDVI52,NDVI53,NDVI54,NDVI55,NDVI56,NDVI57,NDVI58,NDVI59,NDVI60,
              NDVI61,NDVI62,NDVI63,NDVI64,NDVI65,NDVI66,NDVI67,NDVI68,NDVI69,NDVI70,
              NDVI71,NDVI72,NDVI73,NDVI74,NDVI75,
              NDVI1a,NDVI2a,NDVI3a,NDVI4a,NDVI5a,NDVI6a,NDVI7a,NDVI8a,NDVI9a,NDVI10a,
              NDVI11a,NDVI12a,NDVI13a,NDVI14a,NDVI15a,NDVI16a,NDVI17a,NDVI18a,NDVI19a,NDVI20a,
              NDVI21a,NDVI22a,NDVI23a,NDVI24a,NDVI25a,NDVI26a,NDVI27a,NDVI28a,NDVI29a,NDVI30a,
              NDVI31a,NDVI32a,NDVI33a,NDVI34a,NDVI35a,NDVI36a,NDVI37a,NDVI38a,NDVI39a,NDVI40a,
              NDVI41a,NDVI42a,NDVI43a,NDVI44a,NDVI45a,NDVI46a,NDVI47a,NDVI48a,NDVI49a,NDVI50a,
              NDVI51a,NDVI52a,NDVI53a,NDVI54a,NDVI55a,NDVI56a,NDVI57a,NDVI58a,NDVI59a,NDVI60a,
              NDVI61a,NDVI62a,NDVI63a,NDVI64a,NDVI65a,NDVI66a,NDVI67a,NDVI68a,NDVI69a,NDVI70a,
              NDVI71a,NDVI72a,NDVI73a,NDVI74a,NDVI75a)


## Extract Coefficients for Each Plot

Mod.all<- lm(mean ~ year * plot, data= NDVI)
summary(Mod.all)                                         # displays model output for info
coef(Mod.all)                                            # displays model coefficients only, for info
year.coefs.index<- grep("year", names(coef(Mod.all)))    # find the index of the relevant coefficients
year.coef<- coef(Mod.all)[year.coefs.index]
year.coef[-1]<- year.coef[1] + year.coef[-1]             # all coefficients are set to measure the difference to first site
year.coef

NDVIdf <- cbind(read.table(text=names(year.coef)),year.coef)    # converts the year.coef vector to a dataframe
str(NDVIdf)

write.csv(NDVIdf,"D:\\YearCoefficients.csv", row.names = FALSE) # writes a .csv file with the coefficients for each plot
